notunpata/notunpata/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home),
    path('student/', include('student.urls')),
]

notunpata/student/urls.py
from django.urls import path
from . import views

app_name = 'student'

urlpatterns = [
	path('register/', views.register_view, name="register"),
	path('login/', views.login_view, name="login"),
	path('logout/', views.logout_view, name="logout"),
	path('admin_panel/', views.admin_panel, name="admin_panel"),
	path('add_marks/', views.enter_marks, name="add_marks"),
	path('list/', views.student_list, name='student_list'),
	path('add_student/', views.add_student, name="add_student"),
	path('student/', views.student, name="student"),
	path('generate_admit_card/', views.generate_admit_card, name="generate_admit_card"),
	path("marks-by-school/", views.get_marks_by_school, name="marks_by_school"),
	path('all-results/', views.all_results, name="all_results"),
	path('download-results/', views.download_results_pdf, name="download_results_pdf"),
]

notunpata/templates/home.html
{% extends "layout.html"%}
{% block title %}
	Home
{%endblock%}
{% block content%}
	<h1>Welcome to the <strong>Notunpata</strong> student portal</h1><br>
	<a href="{% url 'student:add_student' %}">Add Student</a><br>
	Generate <a href="{% url 'student:generate_admit_card' %}">Admit </a>Card 
	<p>Go to <a href="{% url 'admin:index'%}">Admin</a> page</p>
{%endblock%}

notunpata/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>
		{% block title%}
			Notunpata
		{%endblock%}
	</title>
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
	<!--<script src="{% static 'js/main.js' %}"></script>-->
</head>
<body>
	<nav>
		<a href="/"> Home </a><br>
		{% if user.is_authenticated %}
			<p>Hello, {{ user.username }}</p>
			{% if user.is_superuser %}
				<a href="{% url 'student:admin_panel' %}">Admin</a>
			{% else %}
				<a href="{% url 'student:add_student'%}">Add Student</a>
			{% endif %}
			<a href="{% url 'student:logout' %}">Logout</a>
		{% else %}
			Please <a href="{% url 'student:login' %}">Login</a> or 
			<a href="{% url 'student:register' %}">Register</a>
		{% endif %}
	</nav>
	<main>
		{% block content%}
		{% endblock %}
	</main>
	{%block script%}{%endblock%}
	<footer>
		<p>Copyright &copy; 2025 Notunpata. All rights reserved.</p>
	</footer>
</body>
</html>